CREATE USER ziriwa IDENTIFIED BY letmein12345
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO ziriwa;
GRANT CREATE TABLE TO ziriwa;
GRANT CREATE SEQUENCE TO ziriwa;
GRANT CREATE VIEW TO ziriwa;
GRANT CREATE PROCEDURE TO ziriwa;
