/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Payment = {
  _id: string
  _type: 'payment'
  _createdAt: string
  _updatedAt: string
  _rev: string
  type?: 'investment' | 'benovelent' | 'other'
  member?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'member'
  }
  tier?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'paymentTier'
  }
  year?: number
  month?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
  description?: string
  amountPaid?: number
  paymentDate?: string
  status?: 'pending' | 'completed' | 'failed'
  notes?: string
}

export type Member = {
  _id: string
  _type: 'member'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fullName?: string
  phone?: string
  email?: string
  memberId?: string
  status?: 'active' | 'inactive'
  selectedTier?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'paymentTier'
  }
  tierHistory?: Array<{
    tier?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'paymentTier'
    }
    year?: number
    dateAssigned?: string
    _key: string
  }>
  joinedDate?: string
}

export type PaymentTier = {
  _id: string
  _type: 'paymentTier'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  amount?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Payment
  | Member
  | PaymentTier
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/lib/members/get-all-members.ts
// Variable: ALL_MEMBERS_QUERY
// Query: *[_type == "member"] | order(fullName asc) {      _id,      fullName,      phone,      email,      memberId,      status,      selectedTier->{        _id,        name,        amount,      },      tierHistory[]{        tier->{          _id,          name,          amount,        },        year,        dateAssigned,      },      "payments": *[        _type == "payment"         && references(^._id)      ] {        _id,        type,        amountPaid,        paymentDate,        status,        year,        month,        description,        tier->{          _id,          name,          amount,        },      }    }
export type ALL_MEMBERS_QUERYResult = Array<{
  _id: string
  fullName: string | null
  phone: string | null
  email: string | null
  memberId: string | null
  status: 'active' | 'inactive' | null
  selectedTier: {
    _id: string
    name: null
    amount: number | null
  } | null
  tierHistory: Array<{
    tier: {
      _id: string
      name: null
      amount: number | null
    } | null
    year: number | null
    dateAssigned: string | null
  }> | null
  payments: Array<{
    _id: string
    type: 'benovelent' | 'investment' | 'other' | null
    amountPaid: number | null
    paymentDate: string | null
    status: 'completed' | 'failed' | 'pending' | null
    year: number | null
    month: 1 | 10 | 11 | 12 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | null
    description: string | null
    tier: {
      _id: string
      name: null
      amount: number | null
    } | null
  }>
}>

// Source: ./src/sanity/lib/members/get-member-by-id.ts
// Variable: MEMBER_BY_ID_QUERY
// Query: *[_type == "member" && _id == $memberId] | order(fullName asc) {      _id,      fullName,      phone,      email,      memberId,      status,      selectedTier->{        _id,        name,        amount,      },      tierHistory[]{        tier->{          _id,          name,          amount,        },        year,        dateAssigned,      },      "payments": *[        _type == "payment"         && references(^._id)      ] {        _id,        type,        amountPaid,        paymentDate,        status,        year,        month,        description,        tier->{          _id,          name,          amount,        },      }    }
export type MEMBER_BY_ID_QUERYResult = Array<{
  _id: string
  fullName: string | null
  phone: string | null
  email: string | null
  memberId: string | null
  status: 'active' | 'inactive' | null
  selectedTier: {
    _id: string
    name: null
    amount: number | null
  } | null
  tierHistory: Array<{
    tier: {
      _id: string
      name: null
      amount: number | null
    } | null
    year: number | null
    dateAssigned: string | null
  }> | null
  payments: Array<{
    _id: string
    type: 'benovelent' | 'investment' | 'other' | null
    amountPaid: number | null
    paymentDate: string | null
    status: 'completed' | 'failed' | 'pending' | null
    year: number | null
    month: 1 | 10 | 11 | 12 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | null
    description: string | null
    tier: {
      _id: string
      name: null
      amount: number | null
    } | null
  }>
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n    *[_type == "member"] | order(fullName asc) {\n      _id,\n      fullName,\n      phone,\n      email,\n      memberId,\n      status,\n      selectedTier->{\n        _id,\n        name,\n        amount,\n      },\n      tierHistory[]{\n        tier->{\n          _id,\n          name,\n          amount,\n        },\n        year,\n        dateAssigned,\n      },\n      "payments": *[\n        _type == "payment" \n        && references(^._id)\n      ] {\n        _id,\n        type,\n        amountPaid,\n        paymentDate,\n        status,\n        year,\n        month,\n        description,\n        tier->{\n          _id,\n          name,\n          amount,\n        },\n      }\n    }\n  ': ALL_MEMBERS_QUERYResult
    '\n    *[_type == "member" && _id == $memberId] | order(fullName asc) {\n      _id,\n      fullName,\n      phone,\n      email,\n      memberId,\n      status,\n      selectedTier->{\n        _id,\n        name,\n        amount,\n      },\n      tierHistory[]{\n        tier->{\n          _id,\n          name,\n          amount,\n        },\n        year,\n        dateAssigned,\n      },\n      "payments": *[\n        _type == "payment" \n        && references(^._id)\n      ] {\n        _id,\n        type,\n        amountPaid,\n        paymentDate,\n        status,\n        year,\n        month,\n        description,\n        tier->{\n          _id,\n          name,\n          amount,\n        },\n      }\n    }\n  ': MEMBER_BY_ID_QUERYResult
  }
}
