/** GROQ fragment for measurable activities including detailed tasks (embedded contracts). */
export const MEASURABLE_ACTIVITIES_WITH_TASKS_PROJECTION = /* groq */ `
  measurableActivities[] {
    _key,
    activityType,
    cascadeSource { nodeRole },
    title,
    aim,
    order,
    targetDate,
    status,
    "reportingFrequency": coalesce(reportingFrequency, "n/a"),
    evidence,
    tasks[] | {
      _key,
      "task": coalesce(task, @),
      "priority": coalesce(priority, "medium"),
      "assignee": select(defined(assignee) => assignee->{ _id, "fullName": coalesce(fullName, firstName + " " + lastName), staffId }, null),
      "inputs": select(defined(inputs) => inputs { file { asset->{ _id, url, originalFilename, size, mimeType } }, submittedAt }, null),
      "inputsReviewThread": select(defined(inputsReviewThread) => inputsReviewThread[] {
        _key,
        "author": author->{ _id, "fullName": coalesce(fullName, firstName + " " + lastName) },
        role,
        action,
        message,
        createdAt,
        file { asset->{ _id, url, originalFilename, size, mimeType } },
      }, []),
      "deliverableReviewThread": select(defined(deliverableReviewThread) => deliverableReviewThread[] {
        _key,
        "author": author->{ _id, "fullName": coalesce(fullName, firstName + " " + lastName) },
        role,
        action,
        message,
        createdAt,
        file { asset->{ _id, url, originalFilename, size, mimeType } },
      }, []),
      "status": coalesce(status, "to_do"),
      targetDate,
      "reportingFrequency": coalesce(reportingFrequency, "n/a"),
      expectedDeliverable,
      reportingPeriodStart,
      "periodDeliverables": select(defined(periodDeliverables) => periodDeliverables[] {
        _key,
        periodKey,
        "status": coalesce(status, "pending"),
        submittedAt,
        "deliverable": select(defined(deliverable) => deliverable[] {
          _key,
          file { asset->{ _id, url, originalFilename, size, mimeType } },
          tag,
          locked,
        }, []),
        "deliverableReviewThread": select(defined(deliverableReviewThread) => deliverableReviewThread[] {
          _key,
          "author": author->{ _id, "fullName": coalesce(fullName, firstName + " " + lastName) },
          role,
          action,
          message,
          createdAt,
          file { asset->{ _id, url, originalFilename, size, mimeType } },
        }, []),
      }, []),
      "deliverable": select(defined(deliverable) => deliverable[] {
        _key,
        file { asset->{ _id, url, originalFilename, size, mimeType } },
        tag,
        locked,
      }, []),
    },
  }
`
