import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { format } from 'date-fns'
import { getAttendanceVerificationById } from '@/sanity/lib/meetings/get-attendance-verification'
import { CheckCircle2 } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Verify Attendance Sheet',
  description: 'Verify that this attendance sheet was generated by Phoenix Investment Club',
}

export default async function VerifyAttendancePage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const verification = await getAttendanceVerificationById(id)

  if (!verification) {
    notFound()
  }

  const meeting = verification.meeting
  const formattedGenerated = format(
    new Date(verification.generatedAt),
    'PPpp',
  )
  const formattedMeetingDate = meeting?.meetingDate
    ? format(new Date(meeting.meetingDate), 'PPP')
    : ''

  return (
    <div className='min-h-screen flex flex-col items-center justify-center p-6 bg-muted/30'>
      <div className='max-w-md w-full rounded-lg border bg-background p-8 shadow-sm text-center space-y-6'>
        <div className='flex justify-center'>
          <CheckCircle2 className='h-16 w-16 text-green-600' />
        </div>
        <div>
          <h1 className='text-xl font-semibold'>Authentic Document</h1>
          <p className='text-sm text-muted-foreground mt-1'>
            This attendance sheet was generated by Phoenix Investment Club
          </p>
        </div>
        <div className='space-y-2 text-left border-t pt-6'>
          <div>
            <span className='text-xs text-muted-foreground'>Meeting</span>
            <p className='font-medium'>{meeting?.title ?? '—'}</p>
          </div>
          <div>
            <span className='text-xs text-muted-foreground'>Meeting date</span>
            <p className='font-medium'>{formattedMeetingDate}</p>
          </div>
          <div>
            <span className='text-xs text-muted-foreground'>Generated on</span>
            <p className='font-medium'>{formattedGenerated}</p>
          </div>
          <div>
            <span className='text-xs text-muted-foreground'>Verification ID</span>
            <p className='font-mono text-xs break-all'>{verification._id}</p>
          </div>
        </div>
      </div>
    </div>
  )
}
